FROM golang:1.26

RUN apt-get update && apt-get install -y sqlite3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY db ./db
RUN sqlite3 db/bank.db < db/schema.sql

COPY . .

RUN go build -o ./client/customer/customer ./client/customer/

ENTRYPOINT [ "./client/customer/customer" ]
